import type { FamilyMember, HealthReport, Restriction, HealthMetric, Vital } from '../stores/healthStore';

const MEMBER_ID = 'demo-ari-001';

export const SEED_MEMBERS: FamilyMember[] = [
  {
    id: MEMBER_ID,
    created_at: '2026-01-15T00:00:00Z',
    owner_id: null,
    auth_user_id: null,
    first_name: 'Ari',
    last_name: 'Kaplan',
    date_of_birth: '1995-08-12',
    gender: 'male',
    blood_type: 'O+',
    height_cm: 180,
    weight_kg: 82,
    avatar_url: null,
    notes: 'CEO, Talaria Transportation',
  },
  {
    id: 'demo-sarah-002',
    created_at: '2026-01-15T00:00:00Z',
    owner_id: null,
    auth_user_id: null,
    first_name: 'Sarah',
    last_name: 'Kaplan',
    date_of_birth: '1997-03-22',
    gender: 'female',
    blood_type: 'A+',
    height_cm: 165,
    weight_kg: 62,
    avatar_url: null,
    notes: null,
  },
  {
    id: 'demo-max-003',
    created_at: '2026-02-01T00:00:00Z',
    owner_id: null,
    auth_user_id: null,
    first_name: 'Max',
    last_name: 'Kaplan',
    date_of_birth: '2022-11-05',
    gender: 'male',
    blood_type: 'O+',
    height_cm: 95,
    weight_kg: 15,
    avatar_url: null,
    notes: 'Toddler',
  },
];

export const SEED_REPORTS: HealthReport[] = [
  {
    id: 'rpt-001',
    created_at: '2026-03-10T00:00:00Z',
    member_id: MEMBER_ID,
    report_type: 'blood_test',
    report_date: '2026-03-08',
    title: 'Annual Blood Panel — Quest Diagnostics',
    file_url: null,
    storage_path: null,
    storage_type: 'supabase',
    file_mime_type: 'application/pdf',
    ai_summary: 'Overall healthy blood panel. Cholesterol slightly elevated at 215 mg/dL (borderline). Vitamin D low at 22 ng/mL. All other markers within normal range including CBC, metabolic panel, and thyroid.',
    structured_data: null,
    body_regions: ['blood', 'liver', 'kidneys'],
    processing_status: 'complete',
  },
  {
    id: 'rpt-002',
    created_at: '2026-02-20T00:00:00Z',
    member_id: MEMBER_ID,
    report_type: 'general',
    report_date: '2026-02-18',
    title: 'Annual Physical — Dr. Morrison',
    file_url: null,
    storage_path: null,
    storage_type: 'supabase',
    file_mime_type: 'application/pdf',
    ai_summary: 'Routine physical exam. Blood pressure 128/82 (slightly elevated). Heart and lungs clear. BMI 25.3 (borderline overweight). Recommended increasing cardio exercise and reducing sodium intake.',
    structured_data: null,
    body_regions: ['heart', 'lungs', 'chest'],
    processing_status: 'complete',
  },
  {
    id: 'rpt-003',
    created_at: '2026-01-10T00:00:00Z',
    member_id: MEMBER_ID,
    report_type: 'imaging',
    report_date: '2026-01-08',
    title: 'Lumbar Spine X-Ray',
    file_url: null,
    storage_path: null,
    storage_type: 'supabase',
    file_mime_type: 'image/jpeg',
    ai_summary: 'Mild disc desiccation at L4-L5. No fractures or significant stenosis. Alignment normal. Consistent with early degenerative changes.',
    structured_data: null,
    body_regions: ['spine'],
    processing_status: 'complete',
  },
  {
    id: 'rpt-004',
    created_at: '2025-11-15T00:00:00Z',
    member_id: MEMBER_ID,
    report_type: 'lab_panel',
    report_date: '2025-11-12',
    title: 'Lipid Panel Follow-Up',
    file_url: null,
    storage_path: null,
    storage_type: 'supabase',
    file_mime_type: 'application/pdf',
    ai_summary: 'LDL improved from 142 to 128 mg/dL after dietary changes. HDL stable at 52. Triglycerides normal at 145.',
    structured_data: null,
    body_regions: ['blood', 'heart'],
    processing_status: 'complete',
  },
];

export const SEED_RESTRICTIONS: Restriction[] = [
  {
    id: 'rst-001', created_at: '2026-01-15T00:00:00Z', member_id: MEMBER_ID,
    restriction_type: 'food_allergy', item_name: 'Shellfish', severity: 'critical',
    reaction: 'Anaphylaxis — carries EpiPen', notes: null, source: 'manual', source_report_id: null, confirmed: true,
  },
  {
    id: 'rst-002', created_at: '2026-01-15T00:00:00Z', member_id: MEMBER_ID,
    restriction_type: 'food_intolerance', item_name: 'Dairy', severity: 'warning',
    reaction: 'Bloating, GI discomfort', notes: 'Can tolerate small amounts of hard cheese', source: 'manual', source_report_id: null, confirmed: true,
  },
  {
    id: 'rst-003', created_at: '2026-01-15T00:00:00Z', member_id: MEMBER_ID,
    restriction_type: 'drug_allergy', item_name: 'Sulfa Drugs', severity: 'critical',
    reaction: 'Severe rash, hives', notes: null, source: 'manual', source_report_id: null, confirmed: true,
  },
  {
    id: 'rst-004', created_at: '2026-03-10T00:00:00Z', member_id: MEMBER_ID,
    restriction_type: 'dietary', item_name: 'High Sodium Foods', severity: 'caution',
    reaction: 'Elevated blood pressure', notes: 'Per Dr. Morrison — reduce to <2000mg/day', source: 'ai', source_report_id: 'rpt-002', confirmed: true,
  },
  {
    id: 'rst-005', created_at: '2026-03-10T00:00:00Z', member_id: MEMBER_ID,
    restriction_type: 'food_intolerance', item_name: 'Gluten', severity: 'caution',
    reaction: 'Mild bloating reported', notes: null, source: 'ai', source_report_id: null, confirmed: false,
  },
];

export const SEED_METRICS: HealthMetric[] = [
  // Blood panel
  { id: 'met-01', member_id: MEMBER_ID, metric_name: 'Hemoglobin', metric_value: 15.2, metric_unit: 'g/dL', status: 'normal', ref_range_low: 13.5, ref_range_high: 17.5, body_region: 'blood', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-02', member_id: MEMBER_ID, metric_name: 'WBC', metric_value: 6.8, metric_unit: 'K/uL', status: 'normal', ref_range_low: 4.5, ref_range_high: 11.0, body_region: 'blood', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-03', member_id: MEMBER_ID, metric_name: 'Platelets', metric_value: 245, metric_unit: 'K/uL', status: 'normal', ref_range_low: 150, ref_range_high: 400, body_region: 'blood', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-04', member_id: MEMBER_ID, metric_name: 'Total Cholesterol', metric_value: 215, metric_unit: 'mg/dL', status: 'high', ref_range_low: 0, ref_range_high: 200, body_region: 'heart', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-05', member_id: MEMBER_ID, metric_name: 'LDL Cholesterol', metric_value: 128, metric_unit: 'mg/dL', status: 'high', ref_range_low: 0, ref_range_high: 100, body_region: 'heart', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-06', member_id: MEMBER_ID, metric_name: 'HDL Cholesterol', metric_value: 52, metric_unit: 'mg/dL', status: 'normal', ref_range_low: 40, ref_range_high: 60, body_region: 'heart', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-07', member_id: MEMBER_ID, metric_name: 'Triglycerides', metric_value: 145, metric_unit: 'mg/dL', status: 'normal', ref_range_low: 0, ref_range_high: 150, body_region: 'heart', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-08', member_id: MEMBER_ID, metric_name: 'Vitamin D', metric_value: 22, metric_unit: 'ng/mL', status: 'low', ref_range_low: 30, ref_range_high: 100, body_region: 'blood', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-09', member_id: MEMBER_ID, metric_name: 'Glucose (fasting)', metric_value: 94, metric_unit: 'mg/dL', status: 'normal', ref_range_low: 70, ref_range_high: 100, body_region: 'blood', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-10', member_id: MEMBER_ID, metric_name: 'Creatinine', metric_value: 1.0, metric_unit: 'mg/dL', status: 'normal', ref_range_low: 0.7, ref_range_high: 1.3, body_region: 'kidneys', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-11', member_id: MEMBER_ID, metric_name: 'ALT', metric_value: 28, metric_unit: 'U/L', status: 'normal', ref_range_low: 7, ref_range_high: 56, body_region: 'liver', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-12', member_id: MEMBER_ID, metric_name: 'AST', metric_value: 22, metric_unit: 'U/L', status: 'normal', ref_range_low: 10, ref_range_high: 40, body_region: 'liver', recorded_date: '2026-03-08', source: 'report' },
  { id: 'met-13', member_id: MEMBER_ID, metric_name: 'TSH', metric_value: 2.1, metric_unit: 'mIU/L', status: 'normal', ref_range_low: 0.4, ref_range_high: 4.0, body_region: 'head', recorded_date: '2026-03-08', source: 'report' },
  // Spine
  { id: 'met-14', member_id: MEMBER_ID, metric_name: 'L4-L5 Disc', metric_value: 1, metric_unit: 'grade', status: 'low', ref_range_low: 0, ref_range_high: 0, body_region: 'spine', recorded_date: '2026-01-08', source: 'report' },
  // Previous cholesterol for trend
  { id: 'met-15', member_id: MEMBER_ID, metric_name: 'LDL Cholesterol', metric_value: 142, metric_unit: 'mg/dL', status: 'high', ref_range_low: 0, ref_range_high: 100, body_region: 'heart', recorded_date: '2025-11-12', source: 'report' },
  { id: 'met-16', member_id: MEMBER_ID, metric_name: 'Total Cholesterol', metric_value: 228, metric_unit: 'mg/dL', status: 'high', ref_range_low: 0, ref_range_high: 200, body_region: 'heart', recorded_date: '2025-11-12', source: 'report' },
];

export const SEED_VITALS: Vital[] = [
  { id: 'vit-01', member_id: MEMBER_ID, vital_type: 'blood_pressure', value_primary: 128, value_secondary: 82, unit: 'mmHg', recorded_at: '2026-04-02T08:30:00Z', source: 'manual', notes: null },
  { id: 'vit-02', member_id: MEMBER_ID, vital_type: 'blood_pressure', value_primary: 124, value_secondary: 78, unit: 'mmHg', recorded_at: '2026-03-28T07:45:00Z', source: 'manual', notes: null },
  { id: 'vit-03', member_id: MEMBER_ID, vital_type: 'heart_rate', value_primary: 68, value_secondary: null, unit: 'bpm', recorded_at: '2026-04-03T07:00:00Z', source: 'wearable', notes: 'Resting' },
  { id: 'vit-04', member_id: MEMBER_ID, vital_type: 'weight', value_primary: 181, value_secondary: null, unit: 'lbs', recorded_at: '2026-04-03T06:30:00Z', source: 'manual', notes: null },
  { id: 'vit-05', member_id: MEMBER_ID, vital_type: 'weight', value_primary: 183, value_secondary: null, unit: 'lbs', recorded_at: '2026-03-15T06:30:00Z', source: 'manual', notes: null },
  { id: 'vit-06', member_id: MEMBER_ID, vital_type: 'sleep_score', value_primary: 82, value_secondary: null, unit: '/100', recorded_at: '2026-04-03T06:00:00Z', source: 'wearable', notes: 'Oura Ring' },
  { id: 'vit-07', member_id: MEMBER_ID, vital_type: 'hrv', value_primary: 45, value_secondary: null, unit: 'ms', recorded_at: '2026-04-03T06:00:00Z', source: 'wearable', notes: 'Oura Ring' },
  { id: 'vit-08', member_id: MEMBER_ID, vital_type: 'spo2', value_primary: 98, value_secondary: null, unit: '%', recorded_at: '2026-04-02T22:00:00Z', source: 'wearable', notes: null },
  { id: 'vit-09', member_id: MEMBER_ID, vital_type: 'steps', value_primary: 8420, value_secondary: null, unit: 'steps', recorded_at: '2026-04-02T23:59:00Z', source: 'wearable', notes: null },
  { id: 'vit-10', member_id: MEMBER_ID, vital_type: 'temperature', value_primary: 98.4, value_secondary: null, unit: '°F', recorded_at: '2026-04-02T07:00:00Z', source: 'manual', notes: null },
];
